services:
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus-dev
      ports:
        - "9090:9090"
      volumes:
        - prometheus-data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
      restart: unless-stopped

volumes:
  prometheus-data:
