services:
  mongo:
    image: mongo:8
    container_name: mongo-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass123
      MONGO_INITDB_DATABASE: devdb
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
